version: '3'

services:

    laravel:
        build:
            context: ./laravel
            dockerfile: Dockerfile.prod
            
        image: alladio/laravel
        container_name: laravel
        network:
            - laranet

    nginx:
        image: alladio/nginx:prod
        container_name: nginx
        network:
            - laranet
        ports:
            -"8080:80"

    networks:
     laranet:
        driver: bridge