version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=toor
      - MYSQL_ALLOW_EMPTY_PASSWORD
    networks:
      - node-network

networks:
  node-network:
    driver: bridge